# Generated by Django 2.1.7 on 2019-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=200)),
                ('instructor_age', models.SmallIntegerField()),
                ('instructor_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
