# Generated by Django 2.1.7 on 2019-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='instructor_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
