# Generated by Django 2.1.7 on 2019-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instructors_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='instructor_image',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
